name: Publish Package to Github

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version increment type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  build:
    name: Update to next ${{ github.event.inputs.version_type }} Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Install Bun
        run: npm install -g bun
      - run: bun install
      - run: bun build
      - run: bun run prepack
      # - run: bun run test
      
      # Dynamic version increment based on input or default to patch
      - name: Update version
        run: npm version ${{ github.event.inputs.version_type || 'patch' }} --no-git-tag-version
      
      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      # Commit the updated package.json version
      - name: Commit version update
        run: |
          git add package.json
          git commit -m "build: bump version to $(node -p "require('./package.json').version")"
          git push

      # Execute release script
      - name: Run release script
        run: bash .github/workflows/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}